apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1m
  values:
    controller:
      service:
        type: NodePort
      admissionWebhooks:
        failurePolicy: Ignore # https://github.com/kubernetes/ingress-nginx/issues/5401
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        # Array of inline strategic merge patch definitions as YAML object.
        # Note, this is a YAML object and not a string, to avoid syntax
        # indention errors.      
        patches:
        - patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: all
            spec:
              template:
                spec:
                  tolerations:
                    - key: "ingress-ready"
                      operator: "Equal"
                      value: "true"
                      effect: "NoSchedule"
          target:
            kind: Deployment
            labelSelector: "app.kubernetes.io/instance=ingress-nginx"  