apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wge-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            namespace: flux-system
            name: clusters-service
            port:
              number: 8000
